name: clean_quote_downloader
description: "A clean quote downloader application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  http: ^1.2.0
  share_plus: ^13.1.0
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  adaptive_icon_background: "#091126"
  adaptive_icon_foreground: "assets/images/logo.png"